// <auto-generated />
using System;
using CardReaderBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CardReaderBackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200607200844_firs")]
    partial class firs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CardReaderBackend.Models.AuthCard", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UniqueCardId")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("AuthCard");
                });

            modelBuilder.Entity("CardReaderBackend.Models.EmployeeModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CardReaderBackend.Models.AuthCard", b =>
                {
                    b.HasOne("CardReaderBackend.Models.EmployeeModel", "Employee")
                        .WithOne("AuthCard")
                        .HasForeignKey("CardReaderBackend.Models.AuthCard", "EmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
